### ISSUE TITLE
Alignment of two elements with different parent does not work correctly

### ISSUE THREAD

**Issue by 7evenk** [node-projects/web-component-designer#161]
https://user-images.githubusercontent.com/5232626/198249530-1b3ccac2-4977-4d3a-95b4-3e2734f4811f.mp4

**Comment by 7evenk** [comment]
@cedricfranke28  Maybe this code snippet can help you:

`
  const canvas = originalElement.closest('#node-projects-designer-canvas-canvas');

  if (originalElement != canvas) {
    let actualEl: HTMLElement = originalElement;
    while (actualEl.parentElement != canvas) {
      parentOffsetX += designerCanvas.getNormalizedElementCoordinates(actualEl.parentElement).x;
      parentOffsetY += designerCanvas.getNormalizedElementCoordinates(actualEl.parentElement).y;
      actualEl = actualEl.parentElement;
    }
  }
`

**Comment by cedricfranke28** [comment]
https://user-images.githubusercontent.com/62056776/199720068-423afcee-d9f4-4f94-9dc7-b16df528fca8.mp4

**Comment by cedricfranke28** [comment]
https://user-images.githubusercontent.com/62056776/199939641-13416f7d-df45-451b-a690-0b18ea1e6ec7.mp4

**Comment by 7evenk** [comment]
https://user-images.githubusercontent.com/5232626/199989754-2cd196c7-d7c3-401a-84a7-147e279f955d.mp4
