### ISSUE TITLE
Adding Custom Elements

### ISSUE THREAD

**Issue by boluabraham** [node-projects/web-component-designer#19]
Adding new custom elements with the format(element-element.js) not working. The element was built with polymer/litelement@0.5.2
Also, the property editor for the native elements is not functional.

**Comment by jogibear9988** [comment]
@boluabraham 
I know. Cause of that it's only a preview at the moment. We will work on it. At the moment the Property Editors are not yet functional. But will be within the next weeks.

How do you include your component?

**Comment by jogibear9988** [comment]
Properties do mostly not work at the moment cause i'm unsure how to implement redo/undo. 

It worked before on wizzywid, but I'm not sure if how it's done there is the right way for here.

**Comment by boluabraham** [comment]
@jogibear9988 yeah, how can I include my component? I added the component to the devDependencies and did an npm install but it's not incorporating it

**Comment by jogibear9988** [comment]
i will look to create a wiki page.
dev dep. will be false, cause it‘s a runtime editor, so you will need your comp at runtime!
but it will not automaticly be included... I‘ll take a look

**Comment by jogibear9988** [comment]
Look at my last commits...
They do not work atm at the github webserver (cause of mime types). I will fix that when I split the designer and the sample.

You can now add custom elements and their imports in the json, "look at elments-sample.json"

At the moment for the jsons I also use absolute urls in app-shell.ts, which i will change.

If the import for the component is already done, you can also use only the elment tag like in the elemnts-native.json

**Comment by jogibear9988** [comment]
I'm looking to split the designer and the sample, but this will take a few days... hopefully I get this fixed till march

**Comment by boluabraham** [comment]
I have tried adding the custom elements by following the example in element-sample.json but its still not displaying on the web designer. this is the link to my element
(https://raw.githubusercontent.com/boluabraham/fhir_active_status/master/index.js). could it be that there is a problem with the polymer version?

**Comment by boluabraham** [comment]
Can you create a wiki? it would be helpful

**Comment by jogibear9988** [comment]
mine does also not work. only localy when hosted via polymer serve.
github is not using right mime type for the js files...

**Comment by jogibear9988** [comment]
The usage could be best seen in the demo project: https://github.com/node-projects/web-component-designer-demo

I'll work on Documentation, when I finished most of the work.
Before to much will change .
