### ISSUE TITLE
SVG Overlay moves while zooming

### ISSUE THREAD

**Issue by cedricfranke28** [node-projects/web-component-designer#270]
![ZoomSVGError_WCD](https://user-images.githubusercontent.com/62056776/213987921-22330315-3121-4ea9-a56a-969e35abbd30.gif)

**Comment by jogibear9988** [comment]
edit text extension has nothing to do with svg, this is cause of a doubleclick. the edit text extension needs more work.

**Comment by cedricfranke28** [comment]
Okey, but the warnings above the error occurs while zooming in and out.

**Comment by jogibear9988** [comment]
the genersl calculation for svg seems to be wrong.
also if you select after zooming the rendering is wrong

**Comment by jogibear9988** [comment]
fixed by @kkranich97
