### ISSUE TITLE
Pervent position

### ISSUE THREAD

**Issue by mcode92** [node-projects/web-component-designer#300]
How to prevent the absolute position of element when i changed the style position to static ? now by mouse move changed the position. how to prevent this event and is only with style position moveable ?

**Comment by jogibear9988** [comment]
At the moment, this is our default placement strategy for elements not in a css-grid or css-flexbox.

This could be changed by implementing a own "PlacementService". At the Moment outside of css-grid and Flexbox, the DefaultPlacmentService is used, wich uses placeDesignItem in it's finishPlace Method, wich sets position=absolute.

What placment strategy would you like? Using Transforms? Using Margins? maybe we could ship additional ones.

**Comment by jogibear9988** [comment]
Also, all the Services could be replaced by your own ones.

**Comment by mcode92** [comment]
ok thank you, i will see.

**Comment by jogibear9988** [comment]
@mcode92 if you need to know more, feel free to ask. Also would be nice if we had more positioning options.
