### ISSUE TITLE
Argument is undefined or null error on OSX Silicon

### ISSUE THREAD

**Issue by YiannisBourkelis** [node-projects/web-component-designer#309]
I can not get the add-on to work on OSX. There is no option for 'designer' when right clicking on a .html document.
<img width="383" alt="Screenshot 2023-04-16 at 11 00 57 AM" src="https://user-images.githubusercontent.com/2575796/232283667-fa6b79d7-1c25-44ae-bf19-6a622a37ee8d.png">

If I choose the 'Reopen editor with...' option I can select the ''Designer" but after clicking on it no editor appears and I get the error: " Assertion failed. Argument is undefined or null "

<img width="800" alt="Screenshot 2023-04-16 at 11 01 17 AM" src="https://user-images.githubusercontent.com/2575796/232283687-3994a43c-2da6-4819-9c14-6aebfb025f3e.png">

<img width="1007" alt="Screenshot 2023-04-16 at 11 01 36 AM" src="https://user-images.githubusercontent.com/2575796/232283720-efeb25e1-924c-430f-9a3b-56d5957a4264.png">

**Comment by jogibear9988** [comment]
wich vscode version?
has your document already content? (never tested an empty one)

**Comment by YiannisBourkelis** [comment]
Yes it has content. See attached html file.
[tm1.html.zip](https://github.com/node-projects/web-component-designer/files/11245048/tm1.html.zip)

VS CODE
Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:41:48.638Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No

**Comment by jogibear9988** [comment]
Sorry had no time to look after...

But with my Version 1.0.9 it works for me on MacOS

<img width="1334" alt="image" src="https://github.com/node-projects/web-component-designer/assets/364896/93ece41d-5f91-4243-9d96-40395888a375">
