### ISSUE TITLE
Designer scrollbar 

### ISSUE THREAD

**Issue by mcode92** [node-projects/web-component-designer#310]
I want to change the Vertical scrollbar und make it By default in top, not in the middle of designer document. The Designer document should to be in the Top and there are no Place to scroll upper. How? 
Please See the Screenshots.

**Comment by jogibear9988** [comment]
you need to implement your own version of "DesignerView", this handles the complete scrolling.

At the moment, also the designarea is as big as the element is, cause i find no good solution to make it bigger. But if you specify a size it gets as big as you want.

You could also add support for this to DesignView, and create a pull request. But if you do, do not change the default, cause we use it like this.

Also in this sample: https://node-projects.github.io/web-component-designer-simple-demo/index.html you see how to use only the designerview

**Comment by mcode92** [comment]
Thank you for your response. I have found that using onley the DesignerView is very cumbersome and requires many changes. I would like to increase the size of the design area, and I have tried changing the height in the style area (in the DEV in DesignerCanvas), which resulted in a larger area but also a very large scrollbar. Are there any other ways to change the size?

**Comment by jogibear9988** [comment]
designer view/canvas have the property : designerWidth/designerHeight. see: https://github.com/node-projects/web-component-designer/blob/master/src/elements/widgets/designerView/designerView.ts#L300

**Comment by mcode92** [comment]
I have modified the value of "h-Scrollbar" in "DesignerVier" across all methods, and set the height using "designerCanvas.offsetHeight". This approach has proven to be effective.
