### ISSUE TITLE
Json object cannot be parsed into html attribute

### ISSUE THREAD

**Issue by MatariAbdulwahid** [node-projects/web-component-designer#340]
hi, when we wanted to set a JSON object as Html attributes then it does not parse correctly. I debugged and found that the problem lies in this place and there `item.attributes` does not come the attribute just like the others.

  let attr = item.attributes;
https://github.com/node-projects/web-component-designer/blob/9f13474d32990bfccff9ce1d5e556086be457e8b/src/elements/services/htmlParserService/NodeHtmlParserService.ts#L59

Example:

`<div instansFilter="{"id" : "name" :"abdul"}"></div>`
at Debug also looks like this 

![image](https://github.com/node-projects/web-component-designer/assets/45720924/a63d79a4-76c4-4ec6-aad6-f2639f7ec585)

what you see the error the package `node-html-parser`

**Comment by jogibear9988** [comment]
Try single quotes for the attribute, as json contains double quotes.

**Comment by MatariAbdulwahid** [comment]
with it work but by set the attribute is the default double quotes and here is the problem

**Comment by jogibear9988** [comment]
I‘ll check

**Comment by jogibear9988** [comment]
Where is it the default? If I set a json object via attributes property editor, it works and the attribte starts with a single dash.
You could also use double quotes, but then you have to encode the json double quotes with &quot;

**Comment by jogibear9988** [comment]
Tell me wexactly what you do, but I don't think there is an error.

**Comment by jogibear9988** [comment]
Also the Json would be parsed in the "htmlWriterService"and beatyified, this is the default behavior.

**Comment by jogibear9988** [comment]
@MatariAbdulwahid any more questions?

**Comment by MatariAbdulwahid** [comment]
I have checked the "htmlWriterService" and there is no error, json attributes are written with single quataions and the error was in my code when I set the content (outerHTML) in DocumentContainer-content then the single qutations are converted to double. So there is no error and I thank you for the tips
