### ISSUE TITLE
Extend Path Drawing Tool

### ISSUE THREAD

**Issue by jogibear9988** [node-projects/web-component-designer#51]
- [x] Move Path Points Arround 
- [x] Bugfix for Move Path Points Arround (When pointer is moved to quickly the point will be lost)
- [x]  Change Path Point To Bezier, Quadric Bezire (look at WPF Designer), Arc Segment
- [x]  Close Path via Addon
- [x]  Change Stroke Color when clicked
- [x]  Change Fill Color When Clicked
- [x]  Change Stroke Brush Size

**Comment by jogibear9988** [comment]
More Tools:

- [ ] Draw rect Tool
- [ ] Draw Ellipsis Tool
- [ ] Draw Line Tool

**Comment by jogibear9988** [comment]
- [ ] Think of a way, how we could combine Multiple Path/recht/Circle to a SVG

**Comment by jogibear9988** [comment]
- [ ] Change Movement of Path/Svg. If we try to move the Path, move the whole SVG? Or Move Path inside of SVG?

**Comment by kkranich97** [comment]
- [ ] Add title attributes for the tools

**Comment by kkranich97** [comment]
Add a feature that allows to draw elements centered by pressing crtl
- [ ] centered ellipsis
- [ ] centered rectangle

**Comment by kkranich97** [comment]
> * [x]  Move Path Points Arround
> * [ ]   Change Path Point To Bezier, Quadric Bezire (look at WPF Designer), Arc Segment
> * [ ]   Close Path via Addon
> * [ ]   Change Stroke Color when clicked
> * [ ]   Change Fill Color When Clicked
> * [ ]   Change Stroke Brush Size
