### ISSUE TITLE
Better Scrolling and Zooming, bug with Zoom and Pathpoints

### ISSUE THREAD

**Issue by kkranich97** [node-projects/web-component-designer#67]
### **Bug:** 
- [ ] Points of paths or rects getting shifted when zoomed in or out
- [ ] When Zooming with mouse wheel, the first move is not correct

### **Improvements:**
- [ ] Better Scrolling with Mouse Wheel: Amount of scroll distance should depend on zoom factor
- [x] Scrolling horizontally by holding shift and scrolling with mouse wheel

**Comment by lschirmbrand** [comment]
fixed by pr #83
