### ISSUE TITLE
Move & Resize Turned Objects 

### ISSUE THREAD

**Issue by jogibear9988** [node-projects/web-component-designer#86]
Object could be transformed via CSS. After that also a resize and movement should work.

So:

- Fix movement of Elements when they are not positioned absolute top/left, so also bottom & right should work, and also positioning via Margin, Padding, ... 
- Implement Resizing with all 6 resize Handles. The non implemented ones also need to move the object > see #65 
- Implement movement & resize when a object is transformed (rotated, scewed,...) > see #65 
- Snaplines should also work correctly for those scenarios.

see #105

**Comment by jogibear9988** [comment]
how should resize in grid work? fill next cell? or set width of object?
(or could this be switched by a key?)

**Comment by jogibear9988** [comment]
https://stackoverflow.com/questions/12007971/dragging-resizing-css-transformed-elements

**Comment by 7evenk** [comment]
This issue is covered by #65
